### ISSUE TITLE
Result after 0 ms - Total time of build is incorrect.

### ISSUE THREAD

**Issue by russomi** [Marimoiro/GlobalSlackNotifierPlugin#1]
First off, thank you for this plugin! :+1: 

This is what I am seeing in Slack using `org.jenkins-ci.plugins:global-slack-notifier:1.3` ...

![image](https://user-images.githubusercontent.com/859824/35526522-af105b88-04f5-11e8-8961-9739c1bf4712.png)

All builds have `0 ms` reported.

We are using declarative pipelines and shared libraries on Jenkins ver. 2.89.2.

:pray:

**Comment by DevinFlick** [comment]
+1 also seeing this and would be great to see fixed

**Comment by Marimoiro** [comment]
Thank you for your issue report 
However, It does not reproduce in my jenkins. 

It may take time to identify the cause

![default](https://user-images.githubusercontent.com/5342721/36289774-3a0997d2-1305-11e8-83d3-88e6f097e9dd.png)

**Comment by Marimoiro** [comment]
ok.
I have able to reproduce the problem using declarative pipelines

**Comment by Marimoiro** [comment]
This issue fixed by pipeline job plugin 2.17.

https://wiki.jenkins.io/display/JENKINS/Pipeline+Job+Plugin
Fix JENKINS-46945 - now follow convention of setting Run duration after fireCompleted triggers evaluate

https://github.com/jenkinsci/workflow-job-plugin/releases/tag/workflow-job-2.17
