### ISSUE TITLE
Add support for all Jenkins Environmental Variables

### ISSUE THREAD

**Issue by DevinFlick** [Marimoiro/GlobalSlackNotifierPlugin#2]
http://jenkinshost:8080/env-vars.html/
There a bunch of  environmental vars that could be very useful to users. 

Personally I'd like to be able to set the messages as something like this:
Project:${GIT_URL}, Commit:${GIT_COMMIT} by ${GIT_AUTHOR_NAME}, Jenkins Job:${JOB_NAME} (Job Result), View:${BUILD_URL}

**Comment by Marimoiro** [comment]
already supported.

![image](https://user-images.githubusercontent.com/5342721/36302574-49701e2a-134c-11e8-9be2-4ac0b53aa401.png)
